{% set version = "0.2.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlr3verse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlr3verse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlr3verse/mlr3verse_{{ version }}.tar.gz
  sha256: 1ab5c91e214f089c2db7b543e4ce2f96a9f3b9d06848b8117c03371c20dba451

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bbotk
    - r-data.table
    - r-mlr3 >=0.12.0
    - r-mlr3cluster
    - r-mlr3data
    - r-mlr3filters
    - r-mlr3fselect >=0.8.0
    - r-mlr3hyperband
    - r-mlr3learners
    - r-mlr3mbo
    - r-mlr3misc >=0.11.0
    - r-mlr3pipelines >=0.4.0
    - r-mlr3tuning >=0.17.0
    - r-mlr3tuningspaces >=0.1.1
    - r-mlr3viz
    - r-paradox >=0.6.0
  run:
    - r-base
    - r-bbotk
    - r-data.table
    - r-mlr3 >=0.12.0
    - r-mlr3cluster
    - r-mlr3data
    - r-mlr3filters
    - r-mlr3fselect >=0.8.0
    - r-mlr3hyperband
    - r-mlr3learners
    - r-mlr3mbo
    - r-mlr3misc >=0.11.0
    - r-mlr3pipelines >=0.4.0
    - r-mlr3tuning >=0.17.0
    - r-mlr3tuningspaces >=0.1.1
    - r-mlr3viz
    - r-paradox >=0.6.0

test:
  commands:
    - $R -e "library('mlr3verse')"           # [not win]
    - "\"%R%\" -e \"library('mlr3verse')\""  # [win]

about:
  home: https://mlr3verse.mlr-org.com
  dev_url: https://github.com/mlr-org/mlr3verse
  license: LGPL-3.0-only
  summary: The 'mlr3' package family is a set of packages for machine-learning purposes built in a modular fashion. This wrapper package is aimed to simplify the installation and loading of the core 'mlr3' packages. Get more information about the 'mlr3' project at <https://mlr3book.mlr-org.com/>.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - pascal-git
