{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlr3verse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlr3verse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlr3verse/mlr3verse_{{ version }}.tar.gz
  sha256: 0bd171d258e7d9e00e12f53297bb4a91852cebc09217575c285d4bf732b97e4e

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bbotk >=1.5.0
    - r-data.table
    - r-mlr3 >=0.20.0
    - r-mlr3cluster >=0.1.10
    - r-mlr3data >=0.9.0
    - r-mlr3filters >=0.8.1
    - r-mlr3fselect >=1.2.1
    - r-mlr3hyperband >=0.6.0
    - r-mlr3inferr >=0.1.0
    - r-mlr3learners >=0.9.0
    - r-mlr3mbo >=0.2.8
    - r-mlr3misc >=0.16.0
    - r-mlr3pipelines >=0.7.1
    - r-mlr3tuning >=1.3.0
    - r-mlr3tuningspaces >=0.5.2
    - r-mlr3viz >=0.10.0
    - r-paradox >=1.0.1
  run:
    - r-base
    - r-bbotk >=1.5.0
    - r-data.table
    - r-mlr3 >=0.20.0
    - r-mlr3cluster >=0.1.10
    - r-mlr3data >=0.9.0
    - r-mlr3filters >=0.8.1
    - r-mlr3fselect >=1.2.1
    - r-mlr3hyperband >=0.6.0
    - r-mlr3inferr >=0.1.0
    - r-mlr3learners >=0.9.0
    - r-mlr3mbo >=0.2.8
    - r-mlr3misc >=0.16.0
    - r-mlr3pipelines >=0.7.1
    - r-mlr3tuning >=1.3.0
    - r-mlr3tuningspaces >=0.5.2
    - r-mlr3viz >=0.10.0
    - r-paradox >=1.0.1

test:
  commands:
    - $R -e "library('mlr3verse')"           # [not win]
    - "\"%R%\" -e \"library('mlr3verse')\""  # [win]

about:
  home: https://mlr3verse.mlr-org.com
  dev_url: https://github.com/mlr-org/mlr3verse
  license: LGPL-3.0-only
  summary: The 'mlr3' package family is a set of packages for machine-learning purposes built in a modular fashion. This wrapper package is aimed to simplify the installation and loading of the core 'mlr3' packages. Get more information about the 'mlr3' project at <https://mlr3book.mlr-org.com/>.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - pascal-git
